In [5]:
import pandas as pd
df=pd.read_csv('Chocolate Sales-2.csv')

In [6]:
df.head()

,Sales Person,Country,Product,Date,Amount,Boxes Shipped
0,Jehu Rudeforth,UK,Mint Chip Choco,04-01-2022,"$5,320.00",180
1,Van Tuxwell,India,85% Dark Bars,01-08-2022,"$7,896.00",94
2,Gigi Bohling,India,Peanut Butter Cubes,07-07-2022,"$4,501.00",91
3,Jan Morforth,Australia,Peanut Butter Cubes,27-04-2022,"$12,726.00",342
4,Jehu Rudeforth,UK,Peanut Butter Cubes,24-02-2022,"$13,685.00",184

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3282 entries, 0 to 3281
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Sales Person   3282 non-null   object
 1   Country        3282 non-null   object
 2   Product        3282 non-null   object
 3   Date           3282 non-null   object
 4   Amount         3282 non-null   object
 5   Boxes Shipped  3282 non-null   int64
dtypes: int64(1), object(5)
memory usage: 154.0+ KB

In [9]:
df.describe(include='all')

,Sales Person,Country,Product,Date,Amount,Boxes Shipped
count,3282,3282,3282,3282,3282,3282.000000
unique,25,6,22,504,3013,NaN
top,Kelci Walkden,Australia,50% Dark Bites,13-01-2024,"$2,317.00",NaN
freq,162,615,180,16,5,NaN
mean,NaN,NaN,NaN,NaN,NaN,164.666971
std,NaN,NaN,NaN,NaN,NaN,124.024736
min,NaN,NaN,NaN,NaN,NaN,1.000000
25%,NaN,NaN,NaN,NaN,NaN,71.000000
50%,NaN,NaN,NaN,NaN,NaN,137.000000
75%,NaN,NaN,NaN,NaN,NaN,232.000000
max,NaN,NaN,NaN,NaN,NaN,778.000000

In [10]:
# checking null values
df.isnull().sum()

Sales Person     0
Country          0
Product          0
Date             0
Amount           0
Boxes Shipped    0
dtype: int64

In [11]:
df.columns=df.columns.str.lower()
df.columns=df.columns.str.replace(' ','_')

In [12]:
df.columns

Index(['sales_person', 'country', 'product', 'date', 'amount',
       'boxes_shipped'],
      dtype='object')

In [14]:
# Convert Amount column to numeric
df["amount"] = df["amount"].replace('[\$,]', '', regex=True).astype(float)

In [20]:
# Convert Date column
df["date"] = pd.to_datetime(df["date"], dayfirst=True)

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3282 entries, 0 to 3281
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   sales_person   3282 non-null   object
 1   country        3282 non-null   object
 2   product        3282 non-null   object
 3   date           3282 non-null   datetime64[ns]
 4   amount         3282 non-null   float64
 5   boxes_shipped  3282 non-null   int64
dtypes: datetime64[ns](1), float64(1), int64(1), object(3)
memory usage: 154.0+ KB

In [22]:
# creating month column for dashborad
df["month"] = df["date"].dt.to_period("M")

In [23]:
df.head()

,sales_person,country,product,date,amount,boxes_shipped,month
0,Jehu Rudeforth,UK,Mint Chip Choco,2022-01-04,5320.0,180,2022-01
1,Van Tuxwell,India,85% Dark Bars,2022-08-01,7896.0,94,2022-08
2,Gigi Bohling,India,Peanut Butter Cubes,2022-07-07,4501.0,91,2022-07
3,Jan Morforth,Australia,Peanut Butter Cubes,2022-04-27,12726.0,342,2022-04
4,Jehu Rudeforth,UK,Peanut Butter Cubes,2022-02-24,13685.0,184,2022-02

In [24]:
#performing sales anaysis
#1. Total sales:
df["amount"].sum()

np.float64(19791571.860000003)

In [25]:
#2. sales by country:
df.groupby("country")["amount"].sum().sort_values(ascending=False)

country
Australia      3646444.35
UK             3365388.90
India          3343730.83
USA            3313858.09
Canada         3078495.65
New Zealand    3043654.04
Name: amount, dtype: float64

In [26]:
#3. Top products:
df.groupby("product")["amount"].sum().sort_values(ascending=False)

product
Smooth Sliky Salty      1120201.09
50% Dark Bites          1087659.35
White Choc              1054257.00
Peanut Butter Cubes     1036591.09
Eclairs                  996947.96
99% Dark & Pure          960033.45
85% Dark Bars            955268.24
Organic Choco Syrup      945345.73
Spicy Special Slims      938131.69
Mint Chip Choco          904989.55
Almond Choco             890454.65
Manuka Honey Choco       885208.03
Milk Bars                866273.62
Raspberry Choco          845388.41
After Nines              837215.67
Fruit & Nut Bars         829278.96
Orange Choco             824070.85
Drinking Coco            822245.57
Baker's Choco Chips      799085.67
Choco Coated Almonds     773062.91
Caramel Stuffed Bars     742516.15
70% Dark Bites           677346.22
Name: amount, dtype: float64

In [27]:
#4. Top sales person:
df.groupby("sales_person")["amount"].sum().sort_values(ascending=False)

sales_person
Ches Bonnell           1022599.96
Oby Sorrel             1017204.12
Madelene Upcott        1010028.72
Kelci Walkden          1002929.10
Brien Boise             997326.48
Van Tuxwell             974425.09
Dennison Crosswaite     931849.57
Beverie Moffet          892421.37
Kaine Padly             849062.76
Marney O'Breen          836427.63
Barr Faughny            830826.91
Roddy Speechley         808359.58
Gunar Cockshoot         762283.43
Gigi Bohling            742296.51
Karlen McCaffrey        713832.64
Jehu Rudeforth          708505.03
Jan Morforth            706585.50
Curtice Advani          691797.92
Rafaelita Blaksland     668865.45
Husein Augar            656149.73
Andria Kimpton          648214.81
Mallorie Waber          642903.33
Camilla Castle          628613.13
Dotty Strutley          608101.17
Wilone O'Kielt          439961.92
Name: amount, dtype: float64

In [32]:
#4.1. Top 10 sales person:
df.groupby("sales_person")["amount"].sum().sort_values(ascending=False).head(10)

sales_person
Ches Bonnell           1022599.96
Oby Sorrel             1017204.12
Madelene Upcott        1010028.72
Kelci Walkden          1002929.10
Brien Boise             997326.48
Van Tuxwell             974425.09
Dennison Crosswaite     931849.57
Beverie Moffet          892421.37
Kaine Padly             849062.76
Marney O'Breen          836427.63
Name: amount, dtype: float64

In [28]:
#5. Boxes shipped by country:
df.groupby("country")["boxes_shipped"].sum().sort_values(ascending=False)

country
Australia      99618
Canada         95158
UK             92523
India          89968
USA            81820
New Zealand    81350
Name: boxes_shipped, dtype: int64

In [33]:
#5.1. Top 3 Boxes shipped by country:
df.groupby("country")["boxes_shipped"].sum().sort_values(ascending=False).head(3)

country
Australia    99618
Canada       95158
UK           92523
Name: boxes_shipped, dtype: int64

In [29]:
#Export data for powerbi
df.to_csv("Chocolate_sales_dashboard_dataset.csv", index=False)

In [30]:
import os
os.getcwd()

'C:\\Users\\HP'

In [31]:
import os
os.listdir()

['.anaconda',
 '.conda',
 '.copilot',
 '.ipynb_checkpoints',
 '.ipython',
 '.jupyter',
 '.local',
 '.matplotlib',
 '.python_history',
 '.spyder-py3',
 '.streamlit',
 '.vscode',
 '3D Objects',
 'AppData',
 'Application Data',
 'Chocolate Sales-2.csv',
 'Chocolate_Sales.ipynb',
 'Chocolate_sales_dashboard_dataset.csv',
 'Contacts',
 'Cookies',
 'Copy of VALDATION1 .ipynb',
 'Data.ipynb',
 'Data.ipynb (2).ipynb (2).ipynb (2).ipynb (2)',
 'Detecting water quality final (1).py',
 'Dict_DS.ipynb',
 'Exercise_with_Solution.ipynb',
 'Favorites',
 'FINAL_VALIDATION_.ipynb',
 'handling_missing_data_fillna_dropna_interpolate.ipynb',
 'IntelGraphicsProfiles',
 'Links',
 'LIST_DS.ipynb',
 'Local Settings',
 'logs',
 'Microsoft',
 'ML.ipynb (1).ipynb (1).ipynb (1).ipynb (1)',
 'My Documents',
 'NetHood',
 'NTUSER.DAT',
 'ntuser.dat.LOG1',
 'ntuser.dat.LOG2',
 'NTUSER.DAT{3a694195-6720-11f0-af3e-18473d502670}.TM.blf',
 'NTUSER.DAT{3a694195-6720-11f0-af3e-18473d502670}.TMContainer00000000000000000001.regtrans-ms',
 'NTUSER.DAT{3a694195-6720-11f0-af3e-18473d502670}.TMContainer00000000000000000002.regtrans-ms',
 'ntuser.ini',
 'OneDrive',
 'Oracle',
 'Pandas.ipynb',
 'Pandas_1.ipynb',
 'Pandas_Basics.ipynb',
 'pandas_different_ways_of_creating_dataframe.ipynb',
 'Pandas_groupby_filtering.ipynb',
 'Pandas_iloc_and_loc.ipynb',
 'Pandas_Series .ipynb',
 'PrintHood',
 'python-3.14.3-amd64.exe',
 'PythonPracticeFile.ipynb',
 'Recent',
 'Saved Games',
 'Searches',
 'SendTo',
 'Start Menu',
 'TableauPublicDesktop-64bit-2026-1-0.exe',
 'Templates',
 'Tuple_DS.ipynb',
 'Untitled1.ipynb']